# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c624d68ea72968737de2b109d6e0dc87547430d73bc162cad1d149eaa4ff9ae9b441e75b6c71118c07b1b99ab1150b7cf1b7e156045ce75b60832fad08b2c6d3

test:
  secret_key_base: 4d40c9c5738970f5115cd8f5673c80cb3e085e49b1e008b258fd8bb0efd940b8cbd78d0b74eb78b0319c9998028df59ab2da8c4af9e1270e0e2656cc4950858d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
